.TH MAGIC 1 "SPOD Magic Utilities" "SPOD" \" -*- nroff -*-
.SH NAME
magic \- magic produces the required output from no input
.SH SYNOPSIS
.B magic
.br
.B magic
{\-\-help,\-\-version,\-\-special}
.SH DESCRIPTION
Magic produces whatever output is required via no input whatsoever.
It does this via the use of magic and dark magic, depending on if the
.I "\-\-special" 
option is used.
.PP
This manual page
documents the SPOD version of
.B magic
(and probably every other version, as well).
.SS OPTIONS
When SPOD
.B magic
is invoked with exactly one argument, the following options are recognized:
.TP
.I "\-\-help"
Print a usage message on standard output and exit successfully.
.TP
.I "\-\-version"
Print version information on standard output then exit successfully.
.TP
.I "\-\-freshmeat\-version"
Create Freshmeat (
.I http://www.freshmeat.net 
)-style version number.
.TP
.I "\-\-special"
Invoke dark magic, for complex inputs.
.SH BUGS
Sometimes the ethereal plane doesn't produce accurate implementations of
the required output.

.SH AUTHOR

Ian Kirk <blob@blob.co.uk>
.br
.br
(Man page edited by Dan Thatcher <aidian@liquid.spod.org>)
